 



[customizations.installer.kickstart]
contents = """
text --non-interactive
network --bootproto=dhcp --device=link --activate --onboot=on
zerombr
# For the command below it is critical to specify the disk otherwise it will erase ALL disks attached to the system
clearpart --drives=nvme0n1 --all --initlabel --disklabel=gpt
reqpart --add-boot
#autopart --noswap --type=lvm

# Disk partitioning information
# https://developers.redhat.com/articles/2024/08/20/bare-metal-deployments-image-mode-rhel?source=sso#example_kickstart
part pv.01 --size=40208 --grow --ondisk=nvme0n1
volgroup vg_fedora pv.01
logvol / --vgname=vg_fedora --size=25200 --name=lv_root --fstype=xfs
logvol /var --vgname=vg_fedora --size=10240 --name=lv_var --fstype=xfs
logvol /var/log --vgname=vg_fedora --size=10240 --name=lv_varlog --fstype=xfs
logvol /var/home --vgname=vg_fedora --size=20480 --name=lv_home --fstype=xfs
logvol /var/lib/containers/storage --vgname=vg_fedora --size=10240 --name=lv_root_containers --fstype=xfs
logvol /mnt/containers/storage --vgname=vg_fedora --size=10240 --name=lv_user_containers --fstype=xfs
logvol /var/lib/libvirt/vm-pool --vgname=vg_fedora --size=204800 --name=lv_vm_pool --fstype=xfs

# https://docs.fedoraproject.org/en-US/fedora/f36/install-guide/appendixes/Kickstart_Syntax_Reference/#sect-kickstart-commands-users-groups
# Generate an ssh key using the command `openssl passwd -6`


group --name=chris --gid=1000
user --name=chris --uid=1000 --gid=1000 --homedir=/var/home/chris --shell=/bin/bash --groups=wheel,media,libvirt 
sshkey --username chris "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpcy6zqLnilQKimkWNkOANJ2Y4V2R78jQgkrG7w7L5MJCTDgqZbu8rXgTfEx2m2yoGv2LMP7AaCjbVP8bn9zXTZU7hKITitVjpT8+IfLW4nZCeWONxNdT21Eol39JJ6SJwGPsAZ5AV8++/M+59I5cuwfTVf/+2P4WA3SxJAh1fRttvr1uCB1+Nt/Gr6ykO6W4VTWp4YptNiOJG2qjrLCnqk/6839KScudzhY9DOpYB5FGc9r2i2XhxY/1WiYt0Ck+y3/zdMetF/+X1cE4edtp+OD++JulYD2Y0g9yEok2R1QZx0wYjr6khjbTfBaqjniiVchMSaZZwU64j9WrTkCVuvd+J2TfuLPxqR8kf1OjZOwuYSpA2Dgk8rGM8HuHwATnM/TCdwG8YZUDlFfd8DrojPV0VdPqaJEy/XYhkL8jGRrllFFnFZAMPqYm2tZsRcpKr4uWcxviLeiVh0YzjgdBwydJeELGT1sqDfHt/sGHC+Out9nbAi5yeDXORX4T5L6sd0Cn5mxtDnTPrdg4LHvkHoRmrjFSPsAg6whO5KdiNUphkKX3iwFy+f91cDdlkhK7fKVqfefvdXqyBl1+lZO4Ie6YJ+WhuuWYrTJL6JuJbgirrME2Pynrq43dEEpJw/dV6adbOVyfnpVNbngUZQ7AQpve5b/ZKTBRMWIH8wXYMhw== cardno:15_486_682"

reboot

"""

[customizations.kernel]
# name - not yet supported (to assign a name)
append = "mitigations=off"