FROM registry.redhat.io/rhel9/rhel-bootc:latest

RUN dnf update -y

RUN dnf -y install wget \
    vim-enhanced \
    firewalld \
    cockpit* \
    podman \
    buildah \
    skopeo \
    qemu-kvm \
    libvirt \
    screen \
    openssh-server \
    git \
    lm_sensors

ADD ../files/sudoers.d/wheel-passwordless-sudo /etc/sudoers.d/
ADD ../files/chrony.conf /etc/

RUN mkdir -p -m 777 /var/mnt/vms

