name: Validate bootc build and release

on:
  push:
    branches:
      - main

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: bootc-lab

jobs:
  testbuild:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.RH_REGISTRY_USER }} # service account
        password: ${{ secrets.RH_REGISTRY_PASSWORD }} # service accounts
        registry: registry.redhat.io
    - name: Build Image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ""quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}"
        tags: latest ${{ github.sha }}
        containerfiles: |
         ./Containerfile
  release:
    runs-on: ubuntu-latest
    needs: testbuild
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.FG_PAT }}
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.8.8
      with:
        github_token: ${{ secrets.FG_PAT }}